import {
  assetStackPropsSchema,
  conceptSplitPropsSchema,
  demoFocusFramePropsSchema,
  evidenceClipPropsSchema,
  headlineTakeoverPropsSchema,
  metricSpreadPropsSchema,
  sectionStampPropsSchema,
  workflowPathPropsSchema,
} from '../schema/episode.schema';
import {HeadlineTakeover} from '../components/HeadlineTakeover';
import {PrototypeScene} from '../components/prototype/PrototypeScene';
import {SectionStamp} from '../components/SectionStamp';
import type {ComponentRegistryItem} from './component.types';

const commonStageModes = ['presenter-center', 'presenter-small', 'screen-primary', 'no-presenter'] as const;
const commonSlots = [
  'top-left',
  'top-right',
  'bottom-left',
  'bottom-right',
  'edge-left',
  'edge-right',
  'full-bleed',
  'screen-primary',
  'center-overlay',
] as const;

export const componentRegistry = {
  SectionStamp: {
    name: 'SectionStamp',
    purpose: '章节切换 / 话题标记',
    allowedStageModes: ['presenter-center', 'presenter-small', 'screen-primary', 'no-presenter'],
    allowedSlots: ['top-left', 'top-right', 'edge-left', 'edge-right'],
    requiresSource: false,
    implementationStatus: 'ready',
    schema: sectionStampPropsSchema,
    render: SectionStamp,
  },
  HeadlineTakeover: {
    name: 'HeadlineTakeover',
    purpose: '核心观点 / 强势结论 / 转折句',
    allowedStageModes: ['presenter-center', 'presenter-small', 'screen-primary', 'no-presenter'],
    allowedSlots: ['top-left', 'top-right', 'edge-left', 'edge-right', 'full-bleed', 'center-overlay', 'screen-primary'],
    requiresSource: false,
    implementationStatus: 'ready',
    schema: headlineTakeoverPropsSchema,
    render: HeadlineTakeover,
  },
  ConceptSplit: {
    name: 'ConceptSplit',
    purpose: '概念、新旧方式或前后状态对比',
    allowedStageModes: [...commonStageModes],
    allowedSlots: ['screen-primary', 'full-bleed', 'top-left', 'top-right'],
    requiresSource: false,
    implementationStatus: 'planned',
    schema: conceptSplitPropsSchema,
    render: PrototypeScene,
  },
  EvidenceClip: {
    name: 'EvidenceClip',
    purpose: '新闻、官网、推文、公告和价格页等证据画面',
    allowedStageModes: ['presenter-small', 'screen-primary', 'no-presenter'],
    allowedSlots: ['screen-primary', 'full-bleed'],
    requiresSource: true,
    implementationStatus: 'planned',
    schema: evidenceClipPropsSchema,
    render: PrototypeScene,
  },
  MetricSpread: {
    name: 'MetricSpread',
    purpose: '价格、性能、效率、成本或比例数据展开',
    allowedStageModes: [...commonStageModes],
    allowedSlots: ['top-left', 'top-right', 'screen-primary', 'full-bleed'],
    requiresSource: true,
    implementationStatus: 'planned',
    schema: metricSpreadPropsSchema,
    render: PrototypeScene,
  },
  WorkflowPath: {
    name: 'WorkflowPath',
    purpose: '步骤、Agent 流程或自动化路径',
    allowedStageModes: [...commonStageModes],
    allowedSlots: [...commonSlots],
    requiresSource: false,
    implementationStatus: 'prototype',
    schema: workflowPathPropsSchema,
    render: PrototypeScene,
  },
  DemoFocusFrame: {
    name: 'DemoFocusFrame',
    purpose: '软件操作、网页演示或项目演示聚焦',
    allowedStageModes: ['presenter-small', 'screen-primary'],
    allowedSlots: ['screen-primary'],
    requiresSource: false,
    implementationStatus: 'planned',
    schema: demoFocusFramePropsSchema,
    render: PrototypeScene,
  },
  AssetStack: {
    name: 'AssetStack',
    purpose: '案例、图片、成果或多素材展示',
    allowedStageModes: ['presenter-small', 'screen-primary', 'no-presenter'],
    allowedSlots: ['screen-primary', 'full-bleed', 'top-left', 'top-right'],
    requiresSource: false,
    implementationStatus: 'planned',
    schema: assetStackPropsSchema,
    render: PrototypeScene,
  },
} satisfies Record<string, ComponentRegistryItem>;
