import {
  acidComponentPropsSchema,
  assetStackPropsSchema,
  demoFocusFramePropsSchema,
  evidenceClipPropsSchema,
  metricSpreadPropsSchema,
  narrationEchoLayerPropsSchema,
  remotionTalkEffectPropsSchema,
  talkVideoBasePropsSchema,
  workflowPathPropsSchema,
} from '../schema/episode.schema';
import {AcidComponent} from '../components/AcidComponent';
import {EvidenceClip} from '../components/EvidenceClip';
import {MetricSpread} from '../components/MetricSpread';
import {NarrationEchoLayer} from '../components/NarrationEchoLayer';
import {PrototypeScene} from '../components/prototype/PrototypeScene';
import {RemotionTalkEffect} from '../components/RemotionTalkEffect';
import {TalkVideoBase} from '../components/TalkVideoBase';
import type {ComponentRegistryItem} from './component.types';

const commonStageModes = ['presenter-center', 'presenter-small', 'screen-primary', 'no-presenter'] as const;
const commonSlots = [
  'top-left',
  'top-right',
  'bottom-left',
  'bottom-right',
  'edge-left',
  'edge-right',
  'full-bleed',
  'screen-primary',
  'center-overlay',
] as const;

export const componentRegistry = {
  MediaWall: {
    name: 'MediaWall',
    purpose: '素材墙 / 多来源素材概览',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  Countdown: {
    name: 'Countdown',
    purpose: '时间冲击 / 大数字倒计时',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  ChapterIndex: {
    name: 'ChapterIndex',
    purpose: '章节索引 / 分段目录',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  CountryGap: {
    name: 'CountryGap',
    purpose: '国家对比 / 阵营差距',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  ReleaseTimeline: {
    name: 'ReleaseTimeline',
    purpose: '发布时间线 / 版本节奏',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: true,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  StatsBoard: {
    name: 'StatsBoard',
    purpose: '指标板 / benchmark 面板',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: true,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  Ecosystem: {
    name: 'Ecosystem',
    purpose: '生态列表 / 产品入口清单',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  OpenSourceWave: {
    name: 'OpenSourceWave',
    purpose: '开源浪潮 / 发布清单',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: true,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  MapFocus: {
    name: 'MapFocus',
    purpose: '地图焦点 / 区域与节点强调',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  TimeGap: {
    name: 'TimeGap',
    purpose: '时间差 / 代差大数字',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  PricePage: {
    name: 'PricePage',
    purpose: '价格页 / 价格战与折扣表',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: true,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  TokenBoard: {
    name: 'TokenBoard',
    purpose: 'Token 成本图 / 单位成本比较',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: true,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  AgentExecution: {
    name: 'AgentExecution',
    purpose: 'Agent 执行页 / 聊天与任务轨迹',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: acidComponentPropsSchema,
    render: AcidComponent,
  },
  EvidenceClip: {
    name: 'EvidenceClip',
    purpose: '官方来源、新闻、公告、网页、数据截图等证据展示',
    allowedStageModes: ['presenter-center', 'presenter-small', 'screen-primary', 'no-presenter'],
    allowedSlots: ['top-left', 'top-right', 'edge-left', 'edge-right', 'screen-primary', 'full-bleed'],
    allowedAssetTypes: ['screenshot', 'image', 'chart'],
    requiresSource: true,
    requiresAsset: true,
    implementationStatus: 'ready',
    schema: evidenceClipPropsSchema,
    render: EvidenceClip,
  },
  MetricSpread: {
    name: 'MetricSpread',
    purpose: '价格、成本、性能、速度、比例、时间等关键指标表达',
    allowedStageModes: [...commonStageModes],
    allowedSlots: ['top-left', 'top-right', 'edge-left', 'edge-right', 'screen-primary'],
    requiresSource: true,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: metricSpreadPropsSchema,
    render: MetricSpread,
  },
  NarrationEchoLayer: {
    name: 'NarrationEchoLayer',
    purpose: '普通口播填缝层 / 左侧提要式短句与淡关键词',
    allowedStageModes: ['presenter-center', 'presenter-small'],
    allowedSlots: ['edge-left', 'top-left'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: narrationEchoLayerPropsSchema,
    render: NarrationEchoLayer,
  },
  WorkflowPath: {
    name: 'WorkflowPath',
    purpose: '步骤、Agent 流程或自动化路径',
    allowedStageModes: [...commonStageModes],
    allowedSlots: [...commonSlots],
    requiresSource: false,
    implementationStatus: 'prototype',
    schema: workflowPathPropsSchema,
    render: PrototypeScene,
  },
  DemoFocusFrame: {
    name: 'DemoFocusFrame',
    purpose: '软件操作、网页演示或项目演示聚焦',
    allowedStageModes: ['presenter-small', 'screen-primary'],
    allowedSlots: ['screen-primary'],
    requiresSource: false,
    implementationStatus: 'planned',
    schema: demoFocusFramePropsSchema,
    render: PrototypeScene,
  },
  AssetStack: {
    name: 'AssetStack',
    purpose: '案例、图片、成果或多素材展示',
    allowedStageModes: ['presenter-small', 'screen-primary', 'no-presenter'],
    allowedSlots: ['screen-primary', 'full-bleed', 'top-left', 'top-right'],
    requiresSource: false,
    implementationStatus: 'planned',
    schema: assetStackPropsSchema,
    render: PrototypeScene,
  },
  TalkVideoBase: {
    name: 'TalkVideoBase',
    purpose: '口播视频底层 / 本地视频、音频和 SRT 字幕承载',
    allowedStageModes: ['no-presenter'],
    allowedSlots: ['full-bleed'],
    requiresSource: false,
    requiresAsset: true,
    implementationStatus: 'ready',
    schema: talkVideoBasePropsSchema,
    render: TalkVideoBase,
  },
  RemotionTalkEffect: {
    name: 'RemotionTalkEffect',
    purpose: 'RemotionTalk 本期一次性特效层',
    allowedStageModes: ['presenter-center'],
    allowedSlots: ['edge-left'],
    requiresSource: false,
    requiresAsset: false,
    implementationStatus: 'ready',
    schema: remotionTalkEffectPropsSchema,
    render: RemotionTalkEffect,
  },
} satisfies Record<string, ComponentRegistryItem>;
